branches:
  only:
  - master

assembly_info:
  patch: false

configuration: Release

platform: Any CPU

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build "src\HvA.API" -c %CONFIGURATION% --no-dependencies
  - dotnet build "src\HvA.API.Demo" -c %CONFIGURATION% --no-dependencies

cache:
  - '%USERPROFILE%\.nuget\packages'